robot:
  ros__parameters:
    version_protocol: "1.0.0"
    robot_namespace: "robot_namespace"
    manufacturer_name: "manufacturer_name"
    serial_number: "serial_number"

mqtt_bridge:
  ros__parameters:
    mqtt_address: "localhost"
    mqtt_port: 1883
    ros_to_mqtt:
      - ros_topic: "/{{ robot_namespace }}/cmd_vel"
        mqtt_topic: "{{ robot_namespace }}/cmd_vel"
      - ros_topic: "/{{ robot_namespace }}/status"
        mqtt_topic: "{{ robot_namespace }}/status"
    mqtt_to_ros:
      - mqtt_topic: "{{ robot_namespace }}/commands"
        ros_topic: "/{{ robot_namespace }}/commands"

controller:
  ros__parameters:
    battery_topic: "/{{ robot_namespace }}/battery_state"
    position_topic: "/{{ robot_namespace }}/amcl_pose"
    status_topic: "/{{ robot_namespace }}/status"

adapter:
  ros__parameters:
    movement_command_topic: "/{{ robot_namespace }}/cmd_vel"
    status_topic: "/{{ robot_namespace }}/status"
    vda5050_state_topic: "/{{ robot_namespace }}/vda5050/state"
    vda5050_command_topic: "/{{ robot_namespace }}/vda5050/commands"
